//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAdmissionDocuments.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFAdmissionDocuments.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_add {
            get {
                object obj = ResourceManager.GetObject("cursor_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document set name.
        /// </summary>
        internal static string DocumentSetName_Text {
            get {
                return ResourceManager.GetString("DocumentSetName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display border boxes for keyed text.
        /// </summary>
        internal static string DocumentSetSettingsForm_DisplayBorderBoxes_Text {
            get {
                return ResourceManager.GetString("DocumentSetSettingsForm_DisplayBorderBoxes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed fonts into document.
        /// </summary>
        internal static string DocumentSetSettingsForm_EmbedFonts_Text {
            get {
                return ResourceManager.GetString("DocumentSetSettingsForm_EmbedFonts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce preprinted pages.
        /// </summary>
        internal static string DocumentSetSettingsForm_PrePrintedPage_Text {
            get {
                return ResourceManager.GetString("DocumentSetSettingsForm_PrePrintedPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document set settings.
        /// </summary>
        internal static string DocumentSetSettingsForm_Title {
            get {
                return ResourceManager.GetString("DocumentSetSettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add page(s).
        /// </summary>
        internal static string DocumentSetsListForm_AddPageDocumentSet_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_AddPageDocumentSet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document set.
        /// </summary>
        internal static string DocumentSetsListForm_DocumentSetOps_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_DocumentSetOps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DocumentSetsListForm_EditTemplate_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_EditTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set template values.
        /// </summary>
        internal static string DocumentSetsListForm_EditValues_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_EditValues_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string DocumentSetsListForm_LoadTemplate_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_LoadTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document set.
        /// </summary>
        internal static string DocumentSetsListForm_NewDocumentSet_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_NewDocumentSet_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        internal static string DocumentSetsListForm_NewPageTemplate_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_NewPageTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string DocumentSetsListForm_Reload_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_Reload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string DocumentSetsListForm_RemoveUniversal_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_RemoveUniversal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string DocumentSetsListForm_SettingsGeneral_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_SettingsGeneral_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item settings.
        /// </summary>
        internal static string DocumentSetsListForm_SettingsUniversal_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_SettingsUniversal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string DocumentSetsListForm_TemplateOps_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_TemplateOps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sets List.
        /// </summary>
        internal static string DocumentSetsListForm_Title {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pdf.
        /// </summary>
        internal static string DocumentSetsListForm_ToPfdUniversal_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_ToPfdUniversal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal.
        /// </summary>
        internal static string DocumentSetsListForm_UniversalOps_Text {
            get {
                return ResourceManager.GetString("DocumentSetsListForm_UniversalOps_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap excel48 {
            get {
                object obj = ResourceManager.GetObject("excel48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Path.
        /// </summary>
        internal static string ExcelPath_Text {
            get {
                return ResourceManager.GetString("ExcelPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        internal static string ExportToExcelFile_Text {
            get {
                return ResourceManager.GetString("ExportToExcelFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string FileName_Text {
            get {
                return ResourceManager.GetString("FileName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default font.
        /// </summary>
        internal static string GeneralSettingsForm_DefaultFont_Text {
            get {
                return ResourceManager.GetString("GeneralSettingsForm_DefaultFont_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ui language.
        /// </summary>
        internal static string GeneralSettingsForm_Language_Text {
            get {
                return ResourceManager.GetString("GeneralSettingsForm_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf border box thickness.
        /// </summary>
        internal static string GeneralSettingsForm_PdfBorderThickness_Text {
            get {
                return ResourceManager.GetString("GeneralSettingsForm_PdfBorderThickness_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex history count.
        /// </summary>
        internal static string GeneralSettingsForm_RegexHistoryCount_Text {
            get {
                return ResourceManager.GetString("GeneralSettingsForm_RegexHistoryCount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string GeneralSettingsForm_Title {
            get {
                return ResourceManager.GetString("GeneralSettingsForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imagePlaceholder {
            get {
                object obj = ResourceManager.GetObject("imagePlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Datas.
        /// </summary>
        internal static string InputKeyPropertiesAdditionalDataForm_KeyDatas_Title {
            get {
                return ResourceManager.GetString("InputKeyPropertiesAdditionalDataForm_KeyDatas_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional key field data.
        /// </summary>
        internal static string InputKeyPropertiesAdditionalDataForm_Title {
            get {
                return ResourceManager.GetString("InputKeyPropertiesAdditionalDataForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string Language_Ukrainian {
            get {
                return ResourceManager.GetString("Language_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok_Text {
            get {
                return ResourceManager.GetString("Ok_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture group.
        /// </summary>
        internal static string RegexTesterForm_CaptureGroup_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_CaptureGroup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex help.
        /// </summary>
        internal static string RegexTesterForm_RegexHelp_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_RegexHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex history.
        /// </summary>
        internal static string RegexTesterForm_RegexHistory_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_RegexHistory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression (capture groups are required).
        /// </summary>
        internal static string RegexTesterForm_RegularExpression_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_RegularExpression_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string RegexTesterForm_Result_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_Result_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run regex.
        /// </summary>
        internal static string RegexTesterForm_RunRegex_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_RunRegex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string RegexTesterForm_Text_Text {
            get {
                return ResourceManager.GetString("RegexTesterForm_Text_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Testing.
        /// </summary>
        internal static string RegexTesterForm_Title {
            get {
                return ResourceManager.GetString("RegexTesterForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pages form.
        /// </summary>
        internal static string SelectTemplatesForm_Title {
            get {
                return ResourceManager.GetString("SelectTemplatesForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Template Page.
        /// </summary>
        internal static string TemplateCreateForm_Title {
            get {
                return ResourceManager.GetString("TemplateCreateForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring To Front.
        /// </summary>
        internal static string TemplateEditForm_BringToFrontToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_BringToFrontToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TemplateEditForm_CloseToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_CloseToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TemplateEditForm_DeleteToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_DeleteToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TemplateEditForm_EditToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_EditToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TemplateEditForm_FileToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_FileToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string TemplateEditForm_NewToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_NewToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Template File.
        /// </summary>
        internal static string TemplateEditForm_OpenTemplateFileToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_OpenTemplateFileToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TemplateEditForm_OpenToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_OpenToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallete.
        /// </summary>
        internal static string TemplateEditForm_palleteGroupBox_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_palleteGroupBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string TemplateEditForm_PalleteImage_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PalleteImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TemplateEditForm_PalleteText_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PalleteText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input multiline.
        /// </summary>
        internal static string TemplateEditForm_PalleteTextMultiline_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PalleteTextMultiline_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input(RegEx).
        /// </summary>
        internal static string TemplateEditForm_PalleteTextRegex_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PalleteTextRegex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Input.
        /// </summary>
        internal static string TemplateEditForm_PalleteTextTemplate_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PalleteTextTemplate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallete.
        /// </summary>
        internal static string TemplateEditForm_palleteToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_palleteToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pdf.
        /// </summary>
        internal static string TemplateEditForm_PrintToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PrintToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string TemplateEditForm_PropertiesToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_PropertiesToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegExTest.
        /// </summary>
        internal static string TemplateEditForm_regExTestToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_regExTestToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string TemplateEditForm_SaveAsToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_SaveAsToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Back.
        /// </summary>
        internal static string TemplateEditForm_SendToBackToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_SendToBackToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TemplateEditForm_SettingsToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_SettingsToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash.
        /// </summary>
        internal static string TemplateEditForm_StashToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_StashToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        internal static string TemplateEditForm_Title {
            get {
                return ResourceManager.GetString("TemplateEditForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string TemplateEditForm_ViewToolStrip_Text {
            get {
                return ResourceManager.GetString("TemplateEditForm_ViewToolStrip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string TemplateElementPropertiesForm_Title {
            get {
                return ResourceManager.GetString("TemplateElementPropertiesForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        internal static string TemplateName_Text {
            get {
                return ResourceManager.GetString("TemplateName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display border boxes for keyed text (overriden by document set setting).
        /// </summary>
        internal static string TemplateSettingsForm_DisplayBorderBoxes_Text {
            get {
                return ResourceManager.GetString("TemplateSettingsForm_DisplayBorderBoxes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed fonts into document (overriden by document set setting).
        /// </summary>
        internal static string TemplateSettingsForm_EmbedFonts_Text {
            get {
                return ResourceManager.GetString("TemplateSettingsForm_EmbedFonts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce preprinted pages (overriden by document set setting).
        /// </summary>
        internal static string TemplateSettingsForm_PrePrintedPage_Text {
            get {
                return ResourceManager.GetString("TemplateSettingsForm_PrePrintedPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Settings.
        /// </summary>
        internal static string TemplateSettingsForm_Title {
            get {
                return ResourceManager.GetString("TemplateSettingsForm_Title", resourceCulture);
            }
        }
    }
}
